openapi: 3.0.3
info:
  title: Skeleton Finance Module
  description: The API for the finance module in Skeleton
  version: 0.0.1
servers:
  - url: 'https://example.com'
tags:
  - name: Imports
    description: Importing data
  - name: Settings
    description: Settings for the finance module
  - name: Reports
    description: Reports for the finance module
  - name: Exports
    description: Exporting data
paths:
  # Invoices
  /api/invoices:
    post:
      description: Create a new invoice
      tags:
        - Imports
      requestBody:
        $ref: '#/components/requestBodies/createInvoiceRequest'
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invoiceInfo'
  
  "/api/invoices/{invoiceId}/crediting":
    parameters:
      - name: invoiceId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      description: Create a new credit invoice that completely offsets the original invoice. Does not move any payments.
      tags:
        - Imports
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invoiceInfo'
  
  "/api/invoices/{invoiceId}/payments":
    parameters:
      - name: invoiceId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      description: Create a new payment for an invoice
      tags:
        - Imports
      requestBody:
        $ref: '#/components/requestBodies/createPaymentRequest'
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/paymentInfo'
  
  
  
  # Articles
  /api/settings/articles:
    get:
      tags:
        - Settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/article'
    post:
      tags:
        - Settings
      requestBody: 
        $ref: '#/components/requestBodies/createArticle'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/articleLocation'
  "/api/settings/articles/{articleId}":
    get:
      tags:
        - Settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/article'
    put:
      tags:
        - Settings
      requestBody:
        $ref: '#/components/requestBodies/updateArticle'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/articleLocation'
    delete:
      tags:
        - Settings
      responses:
        '204':
          description: No Content

  # Invoice Templates              
  /api/settings/templates/invoices:
    get:
      tags:
        - Settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/invoiceTemplate'

  # Payment types
  # Might need additional endpoints for connecting to chart of accounts
  # and bank info/account number etc.
  /api/settings/paymentMethods:
    get:
      tags:
        - Settings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/paymentMethod'

  /api/payments:
    get:
      tags:
        - Reports
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/paymentWithId'
  
  
  # Create journal
  /api/journals:
    post:
      tags:
        - Exports
      requestBody: 
        content: 
          application/json:
            schema:
              type: object
              properties: 
                invoices:
                  type: array
                  items:
                    type: string
                    format: uuid
      responses: 
        '200':
          description: OK
          content: 
            application/json:
              schema:
                type: object
                properties: 
                  journalId:
                    type: string
                    format: uuid
  
  
  # Exporting
  "/api/export/{journalId}":
    parameters:
      - name: journalId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      description: Get the journal in CSV or SIE format. Format is specified in the Accept header.
      tags:
        - Exports
      responses:
        '200':
          description: OK
          content:
            text/csv:
              schema:
                type: string
                format: binary
            text/sie:
              schema:
                type: string
                format: binary



components:
  # Request Bodies
  requestBodies:
    createInvoiceRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/invoice'
    createPaymentRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/payment'
    createArticle:
      content:
        application/json:
          schema: 
            $ref: '#/components/schemas/newArticle'
    createNettingRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/netting'
    createAccountRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/account'
    createInvoiceTemplateRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/invoiceTemplate'
    updateInvoiceTemplateRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/invoiceTemplate'
    updateArticle:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/article'
            
  schemas:
    netting:
      type: object
      properties:
        amount:
          type: number
        payDate:
          type: string
          format: date-time
    # Invoice Data
    invoice:
      type: object
      properties:
        invoiceType:
          description: "Specifies what type of Debit Invoice this is, since a Sellers invoice isn't a Credit invoice."
          type: string
          enum:
            - Buyer
            - Seller
            - Other
        
        customer:
          $ref: '#/components/schemas/customer'
        lineItems:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/lineItem'
              - type: string
        ourReference:
          type: string
        yourReference:
          type: string
        externalOrderId:
          description: "The external order reference, e.g. the order number."
          type: string
        paymentTerms:
          type: object
        message:
          description: "A message to the customer."
          type: string
    
    customer:
      type: object
      properties:
        customerReference:
          description: "A stable customer's reference, e.g. customer Id. Not Customer Number."
          type: string
        customerNumber:
          description: "The customer's number, to be shown on the Invoice."
          type: string
        name:
          type: string
        email: # Is this the invoice email, or something else?
          type: string
          format: email
        phone:
          type: string
        mobilePhone:
          type: string
        companyInformation:
          type: object
          properties:
            companyName:
              type: string
            vatNumber:
              type: string
        invoiceAddress:
          $ref: '#/components/schemas/address'
        locale:
          type: string

    address:
      type: object
      properties:
        name:
          type: string
        address1:
          type: string
        address2:
          type: string
        city:
          type: string
        postalCode:
          type: string
        country:
          type: string
    lineItem:
      type: object
      properties:
        articleId:
          type: string
          format: uuid
        description:
          type: string
        unitPrice:
          type: number
        quantity:
          type: number
        externalObjectId:
          description: "The external object reference, e.g. the order line number."
          type: string



    # Invoice Id
    invoiceInfo:
      type: object
      properties:
        invoiceId:
          type: string
          format: uuid
        invoiceNumber:
          type: string
        eventDate:
          type: string
          format: date-time

    # Payment Data
    payment:
      type: object
      properties:
        amount:
          type: number
        currency:
          type: string
        paymentDate:
          type: string
          format: date
        paymentType:
          type: string
          enum:
            - Full
            - Partial
            - Rounding
        paymentMethod:
          type: string
    
    paymentWithId:
      type: object
      properties:
        paymentId:
          type: string
          format: uuid
        eventDate:
          type: string
          format: date-time
        amount:
          type: number
        currency:
          type: string
        paymentDate:
          type: string
          format: date
        paymentType:
          type: string
          enum:
            - Full
            - Partial
            - Rounding
        paymentMethod:
          type: string
    
    # Payment Id
    paymentInfo:
      type: object
      properties:
        paymentId:
          type: string
          format: uuid
        eventDate:
          type: string
          format: date-time

    # Settings
    account:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
        accountNumber:
          type: string
        accountName:
          type: string
        accountTypeId:
          description: "The type of account, e.g. 'Income', 'Expense', 'Asset', 'Liability', 'Equity'. Linked to a parent type."
          type: string
          format: uuid
    
    accountInfo:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
        eventDate:
          type: string
          format: date-time

    accountType:
      type: object
      properties:
        accountTypeId:
          type: string
          format: uuid
        accountTypeName:
          type: string

    accountTypeInfo:
      type: object
      properties:
        accountTypeId:
          type: string
          format: uuid
        eventDate:
          type: string
          format: date-time
    
    
    invoiceTemplate:
      type: object
    invoiceTemplateInfo:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
        eventDate:
          type: string
          format: date-time
    paymentMethod:
      type: object
      properties:
        paymentMethodId:
          type: string
          format: uuid
        paymentMethodName:
          type: string
        accountId:
          type: string
          format: uuid
    article:
      # No VAT linkage right now, as it's very implementation
      # dependent so we leave it for now. 
      # This cannot be a single link, but more of a rule engine.
      type: object
      properties:
        articleId:
          type: string
          format: uuid
        articleName:
          type: string
        articleDescription:
          type: string
    newArticle:
      # No VAT linkage right now, as it's very implementation
      # dependent so we leave it for now. 
      # This cannot be a single link, but more of a rule engine.
      type: object
      properties:
        articleName:
          type: string
        articleDescription:
          type: string
    articleLocation:
      type: object
      properties: 
        articleId:
          type: string
          format: uuid
        eventDate:
          type: string
          format: date-time
    
    period:
      type: object
    
    eventLog:
      type: object
    vat:
      type: object
      properties:
        vatId:
          type: string
          format: uuid
        description:
          type: string
        vatRate:
          type: number
          format: float
        vatType:
          type: string
    
    # Exports
    vatOssReport:
      type: object
    vatRecapitulativeStatement:
      type: object